name: explain
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy
  - scikit-learn
  - jupyter
  - pandas
  - lime
  - eli5
  - causalml
  - lightgbm
  - flake8
  - black
  - isort
  - xgboost
  - shap
  - matplotlib
